### ISSUE TITLE
Questions: holograms.yml written in a different order

### ISSUE THREAD

**Issue by SlimeDog** [FancyMcPlugins/FancyHolograms#117]
I intentionally constructed `holograms.yml` is a specific order. On server restart, the file was rewritten in a different order.

- Can the file be rewritten in the same order in which it was read?
- What is the sort order?
- Can it be changed?

**Comment by kokiriglade** [comment]
there is no sort order, holograms are stored using a `ConcurrentHashMap` internally, which makes no promises on order

**Comment by SlimeDog** [comment]
OK.
