### ISSUE TITLE
/npc scale does not do anything if trying to reset back to scale 1.0

### ISSUE THREAD

**Issue by Xemorr** [FancyMcPlugins/FancyHolograms#122]
![image](https://github.com/user-attachments/assets/df0a1d10-fc22-46af-b1e3-57f0320b0f5e)
If you try and make a NPC a different size, then reset it using /npc scale 1 nothing happens

**Comment by Grabsky** [comment]
I think I've encountered this issue before, so I'd assume it's valid. Should be reported in FancyNpcs repository though. 
https://github.com/FancyMcPlugins/FancyNpcs

**Comment by Xemorr** [comment]
> I think I've encountered this issue before, so I'd assume it's valid. Should be reported in FancyNpcs repository though. https://github.com/FancyMcPlugins/FancyNpcs

oh crap was looking in the wrong repo lol
