### ISSUE TITLE
looking for a hologram nearby 

### ISSUE THREAD

**Issue by Kocimietka7192** [FancyMcPlugins/FancyHolograms#128]
The command is missing, something like in decentholograms - /dh near <distance in blocks> - this command shows what hologram is, for example, 5 blocks next to you.

This is useful for the administration, which does not have access to the server files.

**Comment by Matt-MX** [comment]
Actually this is something I meant to add in #126

**Comment by OliverSchlueter** [comment]
Added in the latest dev build
