### ISSUE TITLE
Seethrough setting does not persist on restart

### ISSUE THREAD

**Issue by ProdPreva1l** [FancyMcPlugins/FancyHolograms#137]
Seethrough setting does not persist on restart.

/holo edit <name> seethrough true

restart server

observe it is no longer in that state

**Comment by OliverSchlueter** [comment]
Do you use the latest version of FancyHolograms?

**Comment by ProdPreva1l** [comment]
yes

**Comment by OliverSchlueter** [comment]
Fixed
