### ISSUE TITLE
FancyNPC scale link issue

### ISSUE THREAD

**Issue by KonoTyran** [FancyMcPlugins/FancyHolograms#139]
when using `/holo edit [hologram] linkWithNpc [npc]` the height of the hologram assumes a scale of 1 causing issues like what is depicted in the following image.
scale 1.5
![image](https://github.com/user-attachments/assets/d613e268-dda9-4fe6-9cd5-9a70ddd52208)
scale 0.5
![image](https://github.com/user-attachments/assets/0babae71-9c53-4be2-9a9f-e0022090b0f5)

**Comment by MiguVT** [comment]
same issue when using poses like sit, etc
