### ISSUE TITLE
Holograms persist when reloading after modifying config file

### ISSUE THREAD

**Issue by virustotalop** [FancyMcPlugins/FancyHolograms#141]
Holograms persist when reloading after modifying the config file.
Steps to reproduce
1. Create a hologram
2. Remove a hologram or update a line for a hologram in the config
3. Run `/fancyholograms reload`

After the reload the old hologram still persists with the old text or the old hologram that was removed from the file.

**Comment by OliverSchlueter** [comment]
Duplicate of #125
