### ISSUE TITLE
npc display name should parse per-player

### ISSUE THREAD

**Issue by Lory9098** [FancyMcPlugins/FancyHolograms#144]
Hi, i'm having this problem that with '&6+&e%player_name%' display name, %player_name%, is the name of the last player joined, the placeholder is working in fact
    messages:
    - '&d%player_name&'

its working properly. I haven't see the code but i'm assuming that you're creating an entity in general, but you should send a packet for the entity without creating it, to avoid this thing.

**Comment by OliverSchlueter** [comment]
Can you explain what exactly is not working / could be optimized? I don't really get the issue

**Comment by Lory9098** [comment]
that the placeholder its not parsing properly in the display name, %player_name%, is the name of the last player joined, but it should be the name of the player that its looking the npc

**Comment by OliverSchlueter** [comment]
What version do you use?

**Comment by Lory9098** [comment]
2.2.2, latest

**Comment by OliverSchlueter** [comment]
Is this an issue for FancyNpcs, FancyHolograms or both?

**Comment by Lory9098** [comment]
fancynpcs

**Comment by OliverSchlueter** [comment]
You opened this issue on the FancyHolograms repo. Could you move it to the FancyNpcs repo please?

**Comment by Lory9098** [comment]
ops sorry
