### ISSUE TITLE
Holograms not loading or displaying on 1.20.2

### ISSUE THREAD

**Issue by tomkimberlin** [FancyMcPlugins/FancyHolograms#43]
Using the 2.1.0 experimental version from the Discord. Running Paper (git-Paper-233 (MC: 1.20.2) currently). No errors in console.

**Comment by OliverSchlueter** [comment]
Is the plugin loaded correctly?

**Comment by tomkimberlin** [comment]
> Is the plugin loaded correctly?

I would assume so? No errors in console. Running Hologram commands doesn’t throw any errors. Holograms just never actually appear.

**Comment by OliverSchlueter** [comment]
Try build 23 (https://fancyplugins.de/fancyholograms/download/)
I think it was a problem with the visibility range

**Comment by tomkimberlin** [comment]
> Try build 23 (https://fancyplugins.de/fancyholograms/download/) I think it was a problem with the visibility range

Still no luck. My existing holograms are not being displayed and newly created holograms are not showing up.

**Comment by OliverSchlueter** [comment]
Do you have any other plugin that could cause this?

**Comment by tomkimberlin** [comment]
> Do you have any other plugin that could cause this?

I just tested on a server with no plugins and it still didn't work. Are you unable to reproduce the issue?

**Comment by OliverSchlueter** [comment]
FancyHolograms does not support bedrock. Is this still a problem with paper & java clients?

**Comment by OliverSchlueter** [comment]
Please reopen, when this is still an issue
