### ISSUE TITLE
Configure versionFetcher connection (blocked by network)

### ISSUE THREAD

**Issue by SlimeDog** [FancyMcPlugins/FancyHolograms#59]
Paper 1.20.4-401
FancyHolograms 2.0.5.50-50

On server start-up, connection attempted to `repo.fancyplugins.de`, blocked by NetworkInterceptor. Please provide configuration option to prevent version checking; we have our own automagical update checker.

**Comment by CoolDCB** [comment]
Hate to be pesky in this post but what's your automagical one :eyes:

**Comment by SlimeDog** [comment]
> Hate to be pesky in this post but what's your automagical one 👀

It's a home-grown script that checks ALL plugins for updates and posts the results to my management web site, run every 15 minutes and on server start-up. So I turn off update checks in all plugins. In addition, I use NetworkInterceptor to block nearly all outgoing network connections.

**Comment by SlimeDog** [comment]
This issue remains in FancyHolograms 2.0.5.54

**Comment by SlimeDog** [comment]
AFK, so won't be able to test for a while.

**Comment by SlimeDog** [comment]
Looks good on build 69. Thanks.
