### ISSUE TITLE
2.0.5 Not support Folia

### ISSUE THREAD

**Issue by paul0665** [FancyMcPlugins/FancyHolograms#66]
server version: Folia 1.20.4 32ff12e
2.0.5

Seem the holograms not even save in file
I suspect that the save_on_changed feature added in version 2.0.5 is broken. it work well in 2.0.4

![image](https://github.com/FancyMcPlugins/FancyHolograms/assets/47947919/5d49d883-47ab-4c07-8d06-642ac442fb8d)

[latest.log](https://github.com/FancyMcPlugins/FancyHolograms/files/14311889/latest.log)

**Comment by OliverSchlueter** [comment]
Should be fixed in the latest dev build: https://fancyplugins.de/FancyHolograms/download/
