### ISSUE TITLE
/hologram delete (hologram)

### ISSUE THREAD

**Issue by KhrysAK47** [FancyMcPlugins/FancyHolograms#74]
Deleting a hologram on latest version to this date does not remove it fully.

**Comment by KhrysAK47** [comment]
It just stays there...

**Comment by KhrysAK47** [comment]
Fixes after server restart though

**Comment by OliverSchlueter** [comment]
I guess you mean "/hologram remove (hologram)". I just tested it with Paper 1.20.4 and it works fine, which version do you use?

**Comment by KhrysAK47** [comment]
The hologram was a billboard, not common hologram.

**Comment by KhrysAK47** [comment]
Paper 1.20.4 is what I am using.

**Comment by OliverSchlueter** [comment]
Does this happen everytime you try to remove a hologram?

**Comment by KhrysAK47** [comment]
> Does this happen everytime you try to remove a hologram?

That is a billboard type, yes.

**Comment by OakLoaf** [comment]
Are there any errors in the console when you attempt to delete the hologram? 
Are you removing the hologram with the command or an API?
