### ISSUE TITLE
Doesn't work for 1.19.4

### ISSUE THREAD

**Issue by Tanerx** [FancyMcPlugins/FancyHolograms#75]
I installed today and get this error for 1.19.4 purpur serer java17
![image](https://github.com/FancyMcPlugins/FancyHolograms/assets/32717109/4e6d7667-1de1-4d24-b2cf-26f8452c4f5d)

Thanks.

**Comment by Grabsky** [comment]
Fixed in c63a771.

You can download latest development build here: https://fancyplugins.de/FancyHolograms/download/
