### ISSUE TITLE
Doesn't work with Spigot

### ISSUE THREAD

**Issue by CptGummiball** [FancyMcPlugins/FancyHolograms#76]
Hello, I use Spigot 1.20.4 and would now like to use FancyHolograms again after I had previously used it on my PaperMC server for a long time. Unfortunately, I discovered that parts of the PaperAPI are queried when starting and the plugin therefore doesn't work with Spigot!

The plugin description only says that PaperMC is recommended and not that it is mandatory. I ask that you either make the plugin work for Spigot OR change the description.

Error: https://paste.gg/p/anonymous/66d3a9de72ef4e408e5dfc5c1ed6f3cb

![image](https://github.com/FancyMcPlugins/FancyHolograms/assets/151415484/2c9c6eea-9891-47f7-83d9-fcde751f2b05)

**Comment by OliverSchlueter** [comment]
It's currently not working with Spigot (only with Paper or a fork of it), I'll update the description shortly. Thank you!
