### ISSUE TITLE
fix text aligments on different versions

### ISSUE THREAD

**Issue by czychuuu** [FancyMcPlugins/FancyHolograms#79]
![image](https://github.com/FancyMcPlugins/FancyHolograms/assets/60987404/750fdab8-91df-422b-bd2f-3ae9a91960cc)

**Comment by OliverSchlueter** [comment]
Set the updateTextInterval to 1s
`/Hologram edit (hologram) updateTextInterval 1s`

**Comment by OliverSchlueter** [comment]
If your problem is not solved please reopen this issue or create a new one.
