### ISSUE TITLE
[Question] Hologram::delete() vs HologramManager::removeHologram()

### ISSUE THREAD

**Issue by DefinitlyEvil** [FancyMcPlugins/FancyHolograms#81]
Hi are there differences betweeen 
```java
Hologram::delete();
```
and
```java
HologramManager::removeHologram();
```
?

Thanks!

**Comment by OakLoaf** [comment]
`Hologram::delete();` just removes the display from the game, `HologramManager::removeHologram();` removes the hologram from the manager and also the save file

**Comment by DefinitlyEvil** [comment]
@OakLoaf Thanks, I assume if I set storage to an empty one then I won't have to call `HologramManager::removeHologram()` then!
