### ISSUE TITLE
CB relocation failed

### ISSUE THREAD

**Issue by SlimeDog** [FancyMcPlugins/FancyHolograms#84]
Per this from Paper developers
```
Once again, please also see the following forum post to make sure your plugins don't break: <https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/>
```
note that with the test Paper server `paper-paperclip-1.20.4-R0.1-SNAPSHOT-mojmap.jar`
```
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to remap plugin jar 'plugins/FancyHolograms-2.0.6.66.jar'
Caused by: java.lang.RuntimeException: Failed to remap plugin jar 'plugins/FancyHolograms-2.0.6.66.jar'
```
Recommended fixes are described in the cited post: [https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/](https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/)

**Comment by OliverSchlueter** [comment]
We are aware of this and going to fix it

**Comment by OliverSchlueter** [comment]
Should be fixed in latest dev build

**Comment by SlimeDog** [comment]
AFK, so won't be able to test for a while.

**Comment by SlimeDog** [comment]
Looks good in build 69. Thanks.
