### ISSUE TITLE
Can items be displayed?

### ISSUE THREAD

**Issue by RedCarl** [FancyMcPlugins/FancyHolograms#88]
Can items be displayed?

**Comment by OakLoaf** [comment]
Items can be displayed with the item hologram type, if you are meaning dropped/bobbing items, then this is not currently a feature.

**Comment by OliverSchlueter** [comment]
Here are the links for the commands:
https://fancyplugins.de/docs/fh-commands.html#create 
https://fancyplugins.de/docs/fh-commands.html#item
