### ISSUE TITLE
[Request] Folia support

### ISSUE THREAD

**Issue by Aitooor** [FancyMcPlugins/FancyHolograms#9]
I see that you have a branch https://github.com/FancyMcPlugins/FancyHolograms/tree/feature/folia

But it not working, the holograms are visible armorstands. And no text shown.

Thanks for your time

**Comment by OliverSchlueter** [comment]
Are you using something like ViaVersion/ViaBackwards? It will only work with server and client version 1.19.4

**Comment by Aitooor** [comment]
> Are you using something like ViaVersion/ViaBackwards? It will only work with server and client version 1.19.4

Yees. That is my mistake sorry.
