### ISSUE TITLE
I added rgb text, doesn't work

### ISSUE THREAD

**Issue by RedCarl** [FancyMcPlugins/FancyHolograms#98]
I added rgb text, doesn't work
<img width="854" alt="image" src="https://github.com/FancyMcPlugins/FancyHolograms/assets/71010647/843a586d-3bf5-4d33-bf00-4704ca3b8817">

**Comment by EXLRALTGHOSTY** [comment]
try using hex color codes instead #000000

**Comment by Grabsky** [comment]
FancyHolograms have support for MiniMessage tags and this is the preferred way of decorating text. See https://docs.advntr.dev/minimessage/format.html for more details.

RGB colors can be represented using HEX format, eg. `<#6EDADA>Example`

There is also a web-viewer: https://webui.advntr.dev/
